version: "3"
services:
  postgres:
    image: postgres
    container_name: basic-api-postres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - "/var/lib/postgresql/data"
